openapi: 3.0.0
info:
  title: Django App API
  version: 1.0.0
paths:
  /api/authors:
    get:
      summary: Retrieve a list of authors
      responses:
        '200':
          description: A list of authors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Author'
  /api/posts/news:
    get:
      summary: Retrieve a list of news posts
      responses:
        '200':
          description: A list of news posts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
  /api/posts/articles:
    get:
      summary: Retrieve a list of article posts
      responses:
        '200':
          description: A list of article posts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
  /api/comments:
    get:
      summary: Retrieve a list of comments
      responses:
        '200':
          description: A list of comments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment'
components:
  schemas:
    Comment:
      type: object
      properties:
        id:
          type: integer
        text:
          type: string
        user:
          $ref: '#/components/schemas/CustomUser'
    Author:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/CustomUser'
        rating:
          type: integer
    Post:
      type: object
      properties:
        id:
          type: integer
          description: The unique identifier for the post
        title:
          type: string
          description: The title of the post
        content:
          type: string
          description: The content of the post
        author:
          $ref: '#/components/schemas/Author'
        created_at:
          type: string
          format: date-time
          description: The date and time when the post was created
    CustomUser:
      type: object
      properties:
        username:
          type: string
        email:
          type: string

